name: lw2019-generics-workshop
version: 0.0.0
synopsis: Exercises for the workshop on generic programming at Lambda World
description: See README at <https://github.com/VictorCMiraldo/lw2019-generics-workshop#README.md>
maintainer: Victor Miraldo <v.cacciarimiraldo@gmail.com>
github: VictorCMiraldo/lw2019-generics-workshop
category: Other

dependencies:
  - base >= 4.9 && < 5
  - sop-core
  - generics-sop  
  - generics-mrsop >= 2.2.0
  - cryptonite
  - memory
  - bytestring
  - QuickCheck
  - hspec

library:
  source-dirs: src/

tests:
  spec: 
    main: Spec.hs
    source-dirs: 
      - tests
    dependencies:
      - lw2019-generics-workshop

